# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        miniature:
            quality: 75

            filters:
                thumbnail: { size: [ 80, 80 ], mode: outbound }

        size_full:

            filters:
                #retailler
                downscale:

                    max: [ 150, 80 ]


        rond:

            filters:
                #decouper
                crop:

                    size: [ 300, 600 ]

